name: hyper_snackbar
description: A highly customizable and animated snackbar package for Flutter.
version: 0.7.0
repository: https://github.com/MakiAno/hyper_snackbar
screenshots:
  - description: 'Demo animation for HyperSnackbar 1'
    path: screenshots/demo1.gif
  - description: 'Demo animation for HyperSnackbar 2'
    path: screenshots/demo2.gif
  - description: 'Demo animation for HyperSnackbar 3'
    path: screenshots/demo3.gif

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  go_router: ^17.0.1
