name: hyper_snackbar
description: A highly customizable and animated snackbar package for Flutter.
version: 0.2.1
repository: https://github.com/MakiAno/hyper_snackbar
screenshots:
  - description: 'Demo animation for HyperSnackbar'
    path: screenshots/demo.gif

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0
